mod auth;
mod client;
mod constants;
mod depot;
mod downloader;
mod games;
mod gogdl;
mod secure_links;

pub use depot::Chunk;
pub use depot::Depot;
pub use depot::DepotFile;
pub use depot::ProductDetails;
pub use downloader::DownloadableFiles;
pub use downloader::DownloadableProduct;
pub use games::GameBuild;
pub use games::GameBuilds;
pub use games::GameDetails;
pub use games::GameLinks;
pub use games::GameScreenshots;
pub use games::GameSummary;
pub use games::OwnedGames;
pub use gogdl::GogDl;
pub use gogdl::GogDlError;
pub use reqwest::Client;
pub use secure_links::SecureLinks;
